version: '3.4'

services:
  senff.idserver.admin:
    image: skoruba-identityserver4-admin:dev
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Senff.IdServer.Admin"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_senff.idserver.admin$
    volumes:
      - C:\Users\alves\source\repos\Senff.IdServer\src\Senff.IdServer.Admin:/app
      - C:\Users\alves\source\repos\Senff.IdServer:/src
      - C:\Users\alves\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_senff.idserver.admin$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_senff.idserver.admin$ \"\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
  senff.idserver.admin.api:
    image: skoruba-identityserver4-admin-api:dev
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Senff.IdServer.Admin.Api"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_senff.idserver.admin.api$
    volumes:
      - C:\Users\alves\source\repos\Senff.IdServer\src\Senff.IdServer.Admin.Api:/app
      - C:\Users\alves\source\repos\Senff.IdServer:/src
      - C:\Users\alves\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_senff.idserver.admin.api$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_senff.idserver.admin.api$ \"\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true

  senff.idserver.sts.identity:
    image: skoruba-identityserver4-sts-identity:dev
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Senff.IdServer.STS.Identity"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_senff.idserver.sts.identity$
    volumes:
      - C:\Users\alves\source\repos\Senff.IdServer\src\Senff.IdServer.STS.Identity:/app
      - C:\Users\alves\source\repos\Senff.IdServer:/src
      - C:\Users\alves\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_senff.idserver.sts.identity$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_senff.idserver.sts.identity$ \"\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
